ticktock/ticktock/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ticktock.views.home', name='home'),
    # url(r'^ticktock/', include('ticktock.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('timeclock.urls', namespace='timeclock')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticktock/timeclock/urls.py
from django.conf.urls import patterns, url

from timeclock import views

urlpatterns = patterns('',
    url(r'^$', views.PunchList.as_view(), name='index'), # Last Few Punches
    url(r'^clock-in/$', views.ClockIn.as_view(), name='clock-in'),
    url(r'^clock-out/$', views.ClockOut.as_view(), name='clock-out'),
    url(r'^record/(?P<pk>\d+)/$', views.RecordDetail.as_view(), name='record-detail'),
    url(r'^record/(?P<pk>\d+)/edit/$', views.RecordUpdate.as_view(), name='record-update'),
    url(r'^record/(?P<pk>\d+)/delete/$', views.RecordDelete.as_view(), name='record-delete'),
    url(r'^record/add/$', views.RecordAdd.as_view(), name='record-add'),
)

ticktock/timeclock/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from time import strftime

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __unicode__(self):
        return self.title

    def get_absolute_url(sefl):
        return reverse('timeclock:project-detail', args=(self.pk,))

class Record(models.Model):
    user = models.ForeignKey(User, editable=True)
    project = models.ForeignKey(Project)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    def elapsed_time(self):
        if self.end_time is not None:
            difftime = self.end_time - self.start_time
            hours, remainder = divmod(difftime.seconds, 3600)
            minutes, seconds = divmod(remainder, 60)
            return "%02d:%02d:%02d" % (hours, minutes, seconds)
        else:
            return None

    def __unicode__(self):
        return "Started " + self.start_time.strftime("%Y-%m-%d %I:%M:%S %p")

    def get_absolute_url(self):
        return reverse('timeclock:record-detail', args=(self.pk,))

ticktock/timeclock/forms.py
from django.forms import ModelForm
from django import forms

from timeclock.models import Record

class UpdateRecordForm(ModelForm):
    class Meta:
        model = Record
        fields = ['project', 'start_time', 'end_time', 'message']

class DateRangeForm(forms.Form):
    from_date = forms.DateField()
    to_date = forms.DateField()

ticktock/timeclock/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.views.generic import ListView, FormView, UpdateView, CreateView, DeleteView, DetailView

from timeclock.models import Record, Project
from timeclock.forms import UpdateRecordForm, DateRangeForm

class PunchList(ListView):
    model = Record
    context_object_name = 'records'

    def get_queryset(self):
        records = Record.objects.filter(user = self.request.user).order_by('-start_time')
        if self.request.GET.items():
            date_range = DateRangeForm(self.request.GET)
            if date_range.is_valid():
                cd = date_range.cleaned_data
                records = records.filter(start_time__range=[cd.get('from_date'), cd.get('to_date')])
        return records

    def get_context_data(self, **kwargs):
        # Get the superclass to do its job
        context = super(PunchList, self).get_context_data(**kwargs)
        
        # Include the date range form
        context['date_range_form'] = DateRangeForm()
        # improve this by supplying an 'initla' to the DateRangeForm

        # Figure out the total time
        total_time = 0
        records = Record.objects.filter(user = self.request.user)
        
        # Did they use the date range in the form?
        if self.request.GET.items():
            date_range = DateRangeForm(self.request.GET)
            if date_range.is_valid():
                cd = date_range.cleaned_data
                records = records.filter(start_time__range=[cd.get('from_date'), cd.get('to_date')])

        for record in records:
            if record.end_time is not None: 
                total_time += (record.end_time - record.start_time).seconds

        hours, remainder = divmod(total_time, 3600)
        minutes, seconds = divmod(remainder, 60)
        total_time_string = "%02d:%02d:%02d" % (hours, minutes, seconds)
        context['total_time'] = total_time_string
        return context


    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PunchList, self).dispatch(*args, **kwargs)


class ClockIn(FormView):
    pass

class ClockOut(FormView):
    pass

class RecordUpdate(UpdateView):
    model = Record
    form_class = UpdateRecordForm

    def get_object(self):
        return get_object_or_404(Record, user = self.request.user, pk = self.kwargs['pk'])

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(RecordUpdate, self).dispatch(*args, **kwargs)

class RecordDelete(DeleteView):
    pass

class RecordAdd(CreateView):
    model = Record
    form_class = UpdateRecordForm

    def get_form(self, form_class):
        form = super(RecordAdd, self).get_form(form_class)
        form.instance.user = self.request.user
        return form


    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(RecordAdd, self).dispatch(*args, **kwargs)

class RecordDetail(DetailView):
    model = Record
    context_object_name = 'record'

    def get_object(self):
        return get_object_or_404(Record, user = self.request.user, pk = self.kwargs['pk'])

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(RecordDetail, self).dispatch(*args, **kwargs)

ticktock/ticktock/templates/base.html
<!DOCTYPE html>
<html>
    <head>

        <title>{% block title %}Tick Tock Time Clock{% endblock %}</title>
        <script src="http://code.jquery.com/jquery.js"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css">
        <!-- Latest compiled and minified JavaScript -->
        <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale: 1.0">
        {% block extrascripts %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <a class="navbar-brand" href="/">Tick Tock</a>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Home</a></li>
                </ul>
                {% if user.is_authenticated %} <!-- I need help here. How to tell if the user is logged in? -->
                    <a href="/accounts/logout/" class="btn btn-default navbar-btn pull-right">Log Out</a></button>
                    <a href="#" class="btn btn-default navbar-btn pull-right">{{ user.username }}</a></button>
                {% else %}
                    <a href="#" class="btn btn-default navbar-btn pull-right">Sign Up</a></button> | 
                    <a href="/accounts/login/" class="btn btn-default navbar-btn pull-right">Log In</a></button>
                {% endif %}
            </div>
            
            <div class="body-content">
                <div class="row">
                    <!-- main content area -->
                    <div class="col-lg-12">
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li class="alert alert-success">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% block content %}
                    {% endblock %}
                    </div>
                    <!-- sidebar -->
                    <div class="col-lg-3">
                    </div>
                </div>

            </div><!-- body-content -->
            <hr>
            <footer>
                Copyright &copy;2013 Dan Purcell. All rights reserved.
            </footer>
        </div><!-- container -->
    </body>
<html>

ticktock/timeclock/templates/timeclock/record_confirm_delete.html
{% extends 'base.html' %}
{% load tz %}

{% block title %}Delete  Time Record Starting {{ record.start_time|localtime }}?{% endblock %}

{% block content %}

<h1>Are you sure?</h1>

<p>Are you sure you want to delete this time card entry?</p>

<form action="." method="post">
{% csrf_token %}
<table class="table">
{{ form }}
</table>
<button class="btn btn-danger">Delete</button>
<a href="{% url 'timeclock:record-detail' object.id %}" class="btn btn-info">Cancel</a>
</form>

{% endblock %}

ticktock/timeclock/templates/timeclock/record_detail.html
{% extends 'base.html' %}
{% load tz %}

{% block title %}Details for Time Record Starting {{ record.start_time|localtime }}{% endblock %}

{% block content %}

<h1>Time Clock Record</h1>

{% if not record %}
<p class="label label-error">No record with record ID {{ record.id }} found.</p>
{% else %}
<table class="table table-striped">
<tr>
    <td>Project:</td><td>{{ record.project }}</td>
</tr>
<tr>
    <td>Start Time:</td><td>{{ record.start_time|date:"Y-m-d g:i a" }}</td>
</tr>
<tr>
    <td>End Time:</td><td>{% if record.end_time %}{{ record.end_time|date:"Y-m-d g:i a" }}{% else %}<span class="label label-danger">in-process</span>{% endif %}</td>
</tr>
<tr>
    <td>Elapsed Time</td><td>{{ record.elapsed_time }}</td>
    {% if record.message %}
</tr>
<tr>
       <td>Message:</td><td>{{ record.message|truncatewords:8 }}</td>
    {% endif %}
</tr>
</table>
<div class="actions">
<h3>Actions</h3>
<a href="#" class="btn btn-default">Return to time clock</a>
<a href="{% url 'timeclock:record-update' record.id %}" class="btn btn-primary">Update this entry</a>
<a href="{% url 'timeclock:record-delete' record.id %}" class="btn btn-danger">Delete this entry</a>
</div>
{% endif %}

{% endblock %}

ticktock/timeclock/templates/timeclock/record_form.html
{% extends 'base.html' %}
{% load tz %}

{% block extrascripts %}
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link rel="stylesheet"  type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/trontastic/jquery-ui.min.css">
<script src="/media/jquery-ui-timepicker-addon.js"></script>

<script>
$(function() {
    $('#id_start_time').datetimepicker();
    $('#id_end_time').datetimepicker();
});
</script>
{% endblock %}

{% block title %}Update Time Record Starting {{ record.start_time|localtime }}{% endblock %}

{% block content %}

<h1>Update Time Clock Record</h1>

<form action="." method="post">
{% csrf_token %}
<table class="table">
{{ form }}
</table>
<button style="btn">Update</button>
</form>

{% endblock %}

ticktock/timeclock/templates/timeclock/record_list.html
{% extends 'base.html' %}

{% block title %}Time Sheet for {{ user.username }}{% endblock %}

{% block content %}

<h1>Time Sheet for {{ user.username }}</h1>

<div>
<form action="." method="get">
<table class="table">
{{ date_range_form }}
</table>
<button class="btn">Search</button>
</form>
</div>


<table class="table table-striped">
<tr>
    <th>Project</th>
    <th>Clock In</th>
    <th>Clock Out</th>
    <th>Time</th>
    <th>Description</th>
    <th></th>
</tr>

{% for record in records %}
<tr>
    <td>{{ record.project }}</td>
    <td>{{ record.start_time|date:"Y-m-d g:i a" }}</td>
    <td>{% if record.end_time %}{{ record.end_time|date:"Y-m-d g:i a" }}{% else %}<span class="label label-danger">in-process</span>{% endif %}</td>
    <td>{{ record.elapsed_time }}</td>
    <td>{{ record.message|truncatewords:8 }}</td>
    <td><a href="{% url 'timeclock:record-detail' record.id %}">details</a></td>
</tr>
{% endfor %}
<tr>
    <td colspan="2"></td>
    <td align="right">Total:</td>
    <td>{{ total_time }}</td>
    <td colspan="2"></td>
</tr>
</table>

<div class="actions">
<h3>Actions</h3>
<a href="#" class="btn btn-primary">Manage Projects</a>
<a href="{% url 'timeclock:record-add' %}" class="btn btn-success">Add New Timeclock Entry</a>
</div>

{% endblock %}